import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { Teikn, validate } from '../lib/index.js';

import { allTokens, themes } from './raw-tokens.js';

// ─── Validate first ─────────────────────────────────────────

const result = validate(allTokens);
if (!result.valid) {
  console.error('Token validation failed:');
  result.issues.forEach(i => console.error(`  [${i.severity}] ${i.token}: ${i.message}`));
  process.exit(1);
}

// ─── Generate ────────────────────────────────────────────────

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const writer = new Teikn({
  generators: [
    new Teikn.generators.Json(),
    // Emits both tokens.mjs (runtime) and tokens.d.ts (types)
    new Teikn.generators.TypeScript(),
    new Teikn.generators.Scss(),
    new Teikn.generators.CssVars(),
  ],
  plugins: [
    new Teikn.plugins.ColorTransformPlugin({ type: 'rgba' }),
    new Teikn.plugins.ScssQuoteValuePlugin(),
  ],
  themes,
  // Writes to dist-js/ so this example doesn't clobber the canonical dist/
  // generated by the comprehensive TypeScript example (`bun run generate-example`).
  outDir: path.resolve(__dirname, 'dist-js'),
});

await writer.transform(allTokens);
