name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["13", "12", "10", "8"]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        id: cache-deps
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies (from network)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          yarn policies set-version
          yarn install --frozen-lockfile --ignore-optional

      - name: Install Dependencies (from cache)
        if: steps.cache-deps.outputs.cache-hit == 'true'
        run: |
          yarn policies set-version
          yarn install --frozen-lockfile --ignore-optional --offline

      - name: Test
        run: yarn test --ci
